### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by ghost** [felipesousa/cordova-resources#1]
MacOS X El Capitan

cordova-resources android

give : 

```
/usr/local/lib/node_modules/cordova-resources/src/index.js:25
            images.push(`${platform}-${resource}.png`);
                        ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova-resources/bin/cordova-resources:4:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

```

**Comment by felipesousa** [comment]
@SimplyLab you have installed in your machine the [Image Magick](https://www.imagemagick.org/script/download.php#macosx)?

I try and all is work normally!

**Comment by felipesousa** [comment]
@SimplyLab you have installed in your machine the [Image Magick](https://www.imagemagick.org/script/download.php#macosx)?

I try and all is work normally!

**Comment by virginielgb** [comment]
I also had an error... Because I'd put the images in the "res" folder instead of placing them at the root of the project :) Just throwing it here in case someone has a similar issue.
